# Generated by Django 3.2.9 on 2022-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('closing_price', models.FloatField(blank=True, max_length=20)),
                ('purchase_price', models.FloatField(blank=True, max_length=20)),
                ('purchase_quantity', models.FloatField(blank=True, max_length=20)),
                ('session', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
