# Generated by Django 3.2.9 on 2022-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_alter_asset_closing_price_alter_asset_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_quantity',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('ticker', 'session')},
        ),
    ]
