# Generated by Django 3.2.9 on 2022-03-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20220304_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='closing_price',
            field=models.FloatField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
