# Generated by Django 3.2.9 on 2022-03-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_auto_20220301_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.FloatField(default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_quantity',
            field=models.FloatField(default=0, max_length=20, null=True),
        ),
    ]
