# Generated by Django 4.0.3 on 2022-03-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_alter_asset_closing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='net_return',
            field=models.FloatField(default=0, max_length=20, null=True),
        ),
    ]
